# Generated by Django 6.0 on 2025-12-10 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MySenzApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='alert_type',
        ),
    ]
