# Generated by Django 6.0 on 2025-12-08 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySenzApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storemanager',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MySenzApp.category'),
        ),
        migrations.AlterField(
            model_name='storemanager',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MySenzApp.service'),
        ),
    ]
