# Generated by Django 6.0 on 2025-12-10 10:21

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySenzApp', '0002_remove_booking_alert_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date',
            new_name='appoinment_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='created_at',
            new_name='booking_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='mangerservices',
            name='category_name',
        ),
        migrations.AddField(
            model_name='booking',
            name='appoinment_time',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), default=list),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_mobile',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mangerservices',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MySenzApp.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='appointment_type',
            field=models.CharField(max_length=20),
        ),
    ]
