# Generated by Django 5.2.8 on 2025-12-09 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySenzApp', '0002_alter_storemanager_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storemanager',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MySenzApp.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storemanager',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MySenzApp.service'),
            preserve_default=False,
        ),
    ]
