# Generated by Django 6.0 on 2025-12-10 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MySenzApp', '0003_rename_date_booking_appoinment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mangerservices',
            name='services_name',
        ),
    ]
