# Generated by Django 5.2.8 on 2025-11-27 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MySenzApp', '0003_storemanager_category_storemanager_service'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
    ]
