# Generated by Django 5.2.8 on 2025-12-09 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySenzApp', '0003_alter_storemanager_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storemanager',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MySenzApp.category'),
        ),
        migrations.AlterField(
            model_name='storemanager',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MySenzApp.service'),
        ),
    ]
