# Generated by Django 5.2.8 on 2025-12-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySenzApp', '0004_alter_storemanager_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storemanager',
            name='category',
        ),
        migrations.RemoveField(
            model_name='storemanager',
            name='service',
        ),
        migrations.AddField(
            model_name='storemanager',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='MySenzApp.category'),
        ),
        migrations.AddField(
            model_name='storemanager',
            name='service',
            field=models.ManyToManyField(blank=True, null=True, to='MySenzApp.service'),
        ),
    ]
