# Generated by Django 5.2.8 on 2025-11-27 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MySenzApp', '0004_alter_customer_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminuser',
            table='adminusers',
        ),
        migrations.AlterModelTable(
            name='appointmentstatuslog',
            table='appoinmentstatuslog',
        ),
        migrations.AlterModelTable(
            name='booking',
            table='booking',
        ),
        migrations.AlterModelTable(
            name='category',
            table='categorys',
        ),
        migrations.AlterModelTable(
            name='service',
            table='services',
        ),
        migrations.AlterModelTable(
            name='store',
            table='store',
        ),
        migrations.AlterModelTable(
            name='storemanager',
            table='storemanager',
        ),
        migrations.AlterModelTable(
            name='timeslot',
            table='timeslot',
        ),
    ]
