# Generated by Django 6.0 on 2025-12-10 10:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySenzApp', '0004_remove_mangerservices_services_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangerservices',
            name='services_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), default=list),
        ),
    ]
