# Generated by Django 5.2.8 on 2025-12-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySenzApp', '0005_remove_storemanager_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storemanager',
            name='category',
        ),
        migrations.RemoveField(
            model_name='storemanager',
            name='service',
        ),
        migrations.AddField(
            model_name='storemanager',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='managers', to='MySenzApp.category'),
        ),
        migrations.AddField(
            model_name='storemanager',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='managers', to='MySenzApp.service'),
        ),
    ]
