# Generated by Django 5.2.8 on 2025-11-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySenzApp', '0005_alter_adminuser_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('new booking', 'New Booking'), ('contacted', 'Contacted'), ('follow-up', 'Follow-Up'), ('intersted', 'Intersted'), ('not intersted', 'Not Intersted'), ('converted', 'Converted'), ('lost', 'LOst')], default='pending', max_length=20),
        ),
    ]
