# Generated by Django 6.0 on 2025-12-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySenzApp', '0006_remove_booking_service_booking_services_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='appoinment_date',
            new_name='appointment_date',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='appoinment_time',
            new_name='appointment_time',
        ),
        migrations.AlterField(
            model_name='booking',
            name='customer_mobile',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('new booking', 'New Booking'), ('contacted', 'Contacted'), ('follow-up', 'Follow-Up'), ('interested', 'Interested'), ('not interested', 'Not Interested'), ('converted', 'Converted'), ('lost', 'Lost')], default='new booking', max_length=20),
        ),
    ]
