# Generated by Django 5.2.8 on 2025-12-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySenzApp', '0006_remove_storemanager_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storemanager',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='storemanager',
            name='services',
        ),
        migrations.AddField(
            model_name='storemanager',
            name='services',
            field=models.JSONField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
