# Generated by Django 5.2.8 on 2025-11-29 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySenzApp', '0006_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.IntegerField(),
        ),
    ]
