# Generated by Django 5.2.8 on 2025-11-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySenzApp', '0007_alter_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='alert_type',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('new booking', 'New Booking'), ('contacted', 'Contacted'), ('follow-up', 'Follow-Up'), ('intersted', 'Intersted'), ('not intersted', 'Not Intersted'), ('converted', 'Converted'), ('lost', 'LOst')], default='new booking', max_length=20),
        ),
    ]
