# Generated by Django 6.0 on 2025-12-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySenzApp', '0007_rename_appoinment_date_booking_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(default='new booking', max_length=20),
        ),
    ]
