# Generated by Django 5.2.8 on 2025-12-09 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySenzApp', '0007_remove_storemanager_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storemanager',
            name='services',
        ),
        migrations.CreateModel(
            name='Mangerservices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150)),
                ('service_name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='MySenzApp.storemanager')),
            ],
            options={
                'db_table': 'managerservices',
            },
        ),
    ]
