# Generated by Django 5.2.8 on 2025-12-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySenzApp', '0008_remove_storemanager_services_mangerservices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mangerservices',
            name='service_name',
        ),
        migrations.AddField(
            model_name='mangerservices',
            name='services_name',
            field=models.JSONField(default=list),
        ),
    ]
