# Generated by Django 6.0 on 2025-12-12 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MySenzApp', '0009_bookingstatus_paymentstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mangerservices',
        ),
    ]
