# Generated by Django 5.2.8 on 2025-12-09 12:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySenzApp', '0009_remove_mangerservices_service_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangerservices',
            name='services_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), default=list, size=None),
        ),
    ]
