# Generated by Django 6.0 on 2025-12-12 11:51

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySenzApp', '0010_delete_mangerservices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mangerservices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_name', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MySenzApp.category')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='MySenzApp.storemanager')),
            ],
            options={
                'db_table': 'managerservices',
            },
        ),
    ]
