# Generated by Django 6.0 on 2025-12-19 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MySenzApp', '0011_mangerservices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicineRequest',
        ),
    ]
