# Generated by Django 6.0 on 2025-12-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('gst', models.CharField(max_length=15)),
                ('category', models.CharField(max_length=50)),
                ('payment', models.CharField(max_length=50)),
                ('credit_days', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
