# Generated by Django 6.0 on 2025-12-18 05:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlowBill', '0002_vendor_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='category',
        ),
        migrations.AddField(
            model_name='vendor',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list),
        ),
    ]
