# Generated by Django 6.0 on 2025-12-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlowBill', '0003_remove_vendor_category_vendor_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='payment',
            field=models.CharField(default='CREDIT', max_length=50),
        ),
    ]
