# Generated by Django 6.0 on 2025-12-22 10:40

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlowBill', '0007_medicine'),
        ('MySenzApp', '0012_delete_medicinerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indent_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suggested_vendors', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indents', to='MySenzApp.store')),
            ],
            options={
                'db_table': 'indent',
            },
        ),
        migrations.CreateModel(
            name='IndentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('indent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='FlowBill.indent')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FlowBill.product')),
            ],
            options={
                'db_table': 'indent_item',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='created', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='FlowBill.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('uom', models.CharField(max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FlowBill.medicine')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FlowBill.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='FlowBill.purchaseorder')),
            ],
        ),
    ]
