# Generated by Django 6.0 on 2025-12-23 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FlowBill', '0009_alter_purchaseorderitem_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
        migrations.DeleteModel(
            name='PurchaseOrderItem',
        ),
    ]
