# Generated by Django 6.0 on 2025-12-24 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlowBill', '0011_purchaseorder_purchaseorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='indentitem',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FlowBill.medicine'),
        ),
        migrations.AlterField(
            model_name='indentitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FlowBill.product'),
        ),
    ]
