# Generated by Django 6.0 on 2025-12-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlowBill', '0013_indent_is_active_medicine_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indent',
            name='status',
            field=models.CharField(max_length=150),
        ),
    ]
