# Generated by Django 6.0 on 2025-12-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlowBill', '0014_alter_indent_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
